[package]
name = "xibao-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37.0", features = ["image"] }
skia-safe = { version = "0.80.1", features = ["textlayout"] }
thiserror = "2.0.3"

[build-dependencies]
pkg-config = "0.3.31"
